#!/bin/tcsh
#
	if(-e $HOME/.samba_top) then
		# set top_data = ` cat -n ~/.samba_top | grep -w 1`; set dir_data = $top_data[2]
		set dir_data = `grep setups $HOME/.samba_top | sed "s/setups //"`
		set instal = "dans $dir_data"
		# set loc_decl = ` cat -n ~/.samba_top | grep -w 3`; set loc = $loc_decl[2]
		set loc = `grep labo $HOME/.samba_top | sed "s/labo //"`
	else
		set dir_data = ""
		set loc_decl = ""
		set instal = "ancienne"
	endif
	echo "      Installation: $instal"
	if ("$loc" == "") then
		set loc = "saclay";
		echo "      Localisation: $loc PAR DEFAUT"
	else
		echo "      Localisation: $loc"
	endif
#
	set xqt=`ps -x -o pid -o start -o pcpu -o command | grep "executables/Samba" | grep -v grep | sed "s/\/executables/ /"`
	if ("$xqt" != "") then
		set dir_data = $xqt[4]
		echo "         Execution: $dir_data"
	endif
	if ("$dir_data" == "") then
		echo "      Etat de Samba indeterminé (pas d'execution en cours, ni de fichier TOP defini)"
	else
		if(-e $dir_data/SambaArgs) then
			set dsk = `grep "^E = " $dir_data/SambaArgs`
			set donnees = $dsk[3]
			set rep = `grep "^e = " $dir_data/SambaArgs`
			set sans_slash = `echo $donnees | sed "s/\///"`
			if ("$sans_slash" == "$donnees") then
				set evts = $dir_data/$donnees/$rep[3]
			else
				set evts = $donnees/$rep[3]
			endif
			echo "        Evenements: $evts"
			ls $evts
		else
			echo "      Samba absent de cet ordinateur"
		endif
	endif
